import "~/styles/globals.css";

import Link from "next/link";

import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <Link href="/" className="block">
            to /
          </Link>
          <Link href="/f1" className="block">
            to /f1
          </Link>
          <Link href="/photo-feed" className="block">
            photo feed
          </Link>
          <Link href="/onboarding" className="block">
            onboarding
          </Link>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
    // </ClerkProvider>
  );
}
